Geekbang/recruitment/jobs/urls.py
from django.urls import path, include
from jobs import views

app_name='jobs'

urlpatterns = [
    path('', views.joblist, name='joblist'),
    path('job/<int:pk>/', views.jobdetail, name='jobdetail'),

    path('newjoblist/',views.JobListView.as_view(), name='newjoblist'),
    path('new_job_detail/<int:pk>/', views.JobDetailView.as_view(), name='new_job_detail'),

    ]

Geekbang/recruitment/recruitment/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('jobs.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from simplesocial import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(),name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include("posts.urls", namespace="posts")),
    path('groups/', include('groups.urls', namespace='groups')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

Geekbang/recruitment/jobs/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
# Create your models here.
JobTypes = [
    (0, '技术类'),
    (1, '产品类'),
    (2, 'Operation'),
    (3, 'Design')
]

Cities = [
    (0, '北京'),
    (1, '上海'),
    (2, 'Melbourne'),
    (3, 'Sydney'),
]

class Job(models.Model):

    job_type = models.SmallIntegerField(blank=False, choices=JobTypes, verbose_name='职位类别')
    job_city = models.SmallIntegerField(blank=False, choices=Cities, verbose_name='City')
    job_name = models.CharField(max_length=255, blank=False, verbose_name='职位名称')
    job_responsibility = models.TextField(max_length=1024, verbose_name='Position')
    job_requirement = models.TextField(max_length=1024, blank=False, verbose_name='Responsibility')
    creator = models.ForeignKey(User, verbose_name='Creator', null=True, on_delete=models.SET_NULL)
    create_date = models.DateTimeField(verbose_name='创建日期', default=datetime.now)
    modified_date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.job_name

Geekbang/recruitment/jobs/views.py
from django.shortcuts import render
from jobs.models import Job, Cities, JobTypes
from django.http import HttpResponse, Http404
from django.template import loader

from django.views import generic
# Create your views here.

def joblist(request):
    job_list = Job.objects.order_by('job_type')
    template = loader.get_template('jobs/joblist.html')
    context = {'job_list':job_list}

    for job in job_list:
        job.the_job_city = Cities[job.job_city][1]
        job.the_job_type = JobTypes[job.job_type][1]

    return HttpResponse(template.render(context))

class JobListView(generic.ListView):
    model = Job
    context_object_name = 'newjoblist'
    template_name = 'jobs/job_list.html'

def jobdetail(request, pk):
    try:
        job = Job.objects.get(pk=pk)
        job.city_name = Cities[job.job_city][1]
    except Job.DoesNotExist:
        raise Http404('No more Job')
    return render(request, 'jobs/job.html', {'job':job})

class JobDetailView(generic.DetailView):
    model = Job
    context_object_name = 'new_job_detail'
    template_name = 'jobs/job_detail.html'

Geekbang/recruitment/jobs/templates/jobs/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <title></title>
    </head>
    <body>
        <div class="container">

        <h1>Django Technology</h1>
        <p></p>

        </div>

        {% block content %}

        {% endblock %}

    </body>
</html>

Geekbang/recruitment/jobs/templates/jobs/job.html
{% extends "jobs/base.html" %}

{% block content %}
    <div class='container'>
        <a href="{% url 'jobs:joblist' %}" style="color:blue">Return to Job List</a>
        <div class="jumbotron">
        {% if job %}
        <div class="positon_name">
            <h2>Position Name: {{job.job_name}}</h2>
            <p>City: {{job.city_name}}</p>
        </div>
        <hr>
        <div class="postion_responsibility" style="width:680px;">
            <h3>Position Responsibility:</h3>
            <p>{{job.job_responsibility}}</p>
        <br>
        </div>
        <hr>
        <div class="position_requirement" >
            <h3>Position Requirement:</h3>
            <p>{{job.job_requirement}}</p>
        </div>
        <br>
        <div class="apply_postion">
            <input type="button" class="btn btn-primary" value="APPLY">
        </div>
        {% else %}
        <p>Position not available</p>
        {% endif %}

    </div>
    </div>
{% endblock %}

Geekbang/recruitment/jobs/templates/jobs/job_detail.html
{% extends "jobs/base.html" %}

{% block content %}
    <div class="container">
        <a href="{% url 'jobs:newjoblist' %}" style="color:blue">Return to Job List</a>
        <div class="jumbotron">
            <h1>This is CLASS BASED VIEW!</h1>
            <hr>
            {% if new_job_detail %}
            <div class="positon_name" >
                <h2>POSITION: {{new_job_detail.job_name}}</h2>
                <p>City: {{new_job_detail.get_job_city_display}}</p>
            </div>
            <hr>
            <div class="postion_responsibility" style='width:600px'>
                <h3>RESPONSIBILITY:</h3>
                <p>{{new_job_detail.job_responsibility}}</p>
            <br>
            </div>
            <hr>
            <div class="position_requirement" style='width:600px' >
                <h3>REQUIREMENT:</h3>
                <p>{{new_job_detail.job_requirement}}</p>
            </div>
            <br>
            <div class="apply_postion">
                <input type="button" class="btn btn-primary" value="APPLY">
            </div>
            {% else %}
            <p>Position not available</p>
            {% endif %}
        </div>

    </div>
{% endblock %}

Geekbang/recruitment/jobs/templates/jobs/job_list.html
{% extends "jobs/base.html" %}

{% block content %}
<div class="container">

<div class="jumbotron">
<h3>Welcome to the NEW CLASS BASED VIEW Django world!</h3>
{% if newjoblist %}
<ul>
    {% for x in newjoblist %}

        <li>
            {{x.get_job_type_display}}:
            <a href='{% url 'jobs:new_job_detail' x.pk %}' style="color:blue">{{x.job_name}}</a>
            {{x.get_job_city_display}}
        </li>

    {% endfor %}
</ul>
{% else %}
<p>No jobs are available....</p>
{% endif %}


</div>
</div>

{% endblock %}

Geekbang/recruitment/jobs/templates/jobs/joblist.html
{% extends "jobs/base.html" %}

{% block content %}

<div class="container">
    <div class="jumbotron">

    <h3>Welcome to the Django world!</h3>

{% if job_list %}
<ul>
    {% for job in job_list %}

        <li>
            {{job.the_job_type}}:
            <a href="/job/{{job.id}}/">{{job.job_name}}</a>
            {{job.the_job_city}}
        </li>

    {% endfor %}
</ul>
{% else %}
<p>No jobs are available.</p>
{% endif %}

<p>Code in different way to get the same value:</p>
{% if job_list %}
<ul>
    {% for job in job_list %}

        <li>
            {{job.get_job_type_display}}:
            <a href="/job/{{job.id}}/">{{job.job_name}}</a>
            {{job.get_job_city_display}}
        </li>

    {% endfor %}
</ul>
{% else %}
<p>No jobs are available.</p>
{% endif %}

</div>

</div>
{% endblock %}